replicaCount: 1
image:
  repository: hello_api
  pullPolicy: IfNotPresent
  tag: 1.0.0-123-test
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
service:
  type: NodePort
  port: 9080
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
app:
  serviceOwner: ""
